language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: MjxoWQXABP+He8u/yjjp+1T0P+gb2Oga8zIgUa37JMCDkinCfkcK/2aDdXTyosz2lRg0Ey6CMcmV1RBRJQjRM1FMbVaYe7Rw9DJyTWnAXaa8BcgTeMlSw+mbbRlKl4tsOgNIFhfQlmwdDtoHUAPy2eVT3rv1w0RqoW0o4/vWgKILjI3OQmfn4LMc+DXFC9xbV8fl6x2EKuh2tHnFawRihurHtT53rrHJeeYcBex4KtvR8LAat/uJYHvzmZ4At6GlsWjg2Syh1Msm2QfV/7zNXOsHTJYjuOUh6vzqQWfN9zjKD4whh72FSesP/2q9O3Hmbha3SpPUQ+wW3FIYO9uz7sFPCft1hEUjQL67cochQemhTZ3UMmg6oanietx4+ISDrllGuNf9QUwZYR7TDGhm5HVUEgrV8+W9lSagnQ4b8wSxXb3C1DbDvHjPjTL0M4dK3DHOhFA/yzGlZXGtjDYRPz/HZUJW6UPqNqSqwegFDaLT8uo+aOYoO4k/dMmFUJ2FOwhgimycrh8Whv44iL/Sg9Qb7H7Do1ch3xHGbmQANwtnuWjOBWy58yFfr9y5SgMwIzfQqRK8bYS1ZZVYppXEhhFZMNlpkSspfGTLfN7LzZaQxdgBJWozCJEg148zwoR8D9gyn5d3ZIwTN0cJtHwJd1Ong6IZHpVWJOOLB1ZSBA0=
  app: ratebeerwadror
  on:
    repo: karoliinaemilia/wadror
  run: rails db:migrate
env:
  secure: yJ56i6Bv0N5uDQKtF+COFsrROSSVSLoH3p2eT5Z9w00LZ8iAL0IAzQZVqAwp1z8Jo1V4TqZjre4lOAiV3qCB01gCG9P5IR+08KTpnlzPeWY96lDiM4TK3kOJrL2juzerE54CCJSbcQ+TWDLh9CYw4o8rJlcSn1RUgiwrhKjzpFQx7hwTm2/XfUlcfYEJUmDk7vJBD2AnbHau+FB9aA4PAIqdPB+FnToJahgTwoPOO2CswwlulxM0E2NdaWocLJ97G+gdwMI3+6MFCTRFEUnv/8F1EvIOo8PAD0bsJVpYVKJj+4XSSzjbtXeyyEGr/FaWvWwcgvPKcHVIzvgF1Qx+t4UvMhcA4rKFI0iU4Y0V+evqou2Y4EBT9ukByCnBtqqkx+O5ty7ZgfIpiU4lDGHthiXEhdvc1SS26WtooJR+ZFGYzqpl+E2thzeQ6YdpsFFzO3ZphdvZgKaW+ZxJ5d5sFW6rXA3k5G61zoRRBWtcEjFgw/LrrCaxN7kuL7Gh3gJn6XDijcOtz75B4zDEDomExy3Ns9OeZ3z9BD3dajtG3FKFvWNhkwLiJchr90mvqmqLkaxSnyeDw2PDrRKCXFE0U8Y1d1ESPARido+C3RUPGGCTcq2KRLvwgjEYgrqyye454yA75FjkfwwwzTVk8UYAWJf6VbB+GOacSgjtqvjZ1yo=
